easy_admin:
    site_name: 'Produits testés'
    design:
        brand_color: '#0072b9'
        color_scheme: 'dark'
        templates:
            field_id: 'admin/fields/_id.html.twig'
        form_theme: vertical

    list:
        title: 'Liste des %%entity_label%%'
        actions: 
            - {name: show, icon: eye, label: ''}
            - {name: edit, icon: pencil, label: ''}
            - {name: delete, icon: trash, label: ''}
            - {name: new, icon: plus, label: 'Ajouter'}

    entities:
        Langue:
            label: 'Langues'
            class: App\Entity\Langue
            list:
                title: 'Liste des langues'
                fields: 
                    - {property: id, label: ID}
                    - {property: nom, label: Langue}
                    - {property: label, label: Code langue}
                    - {property: urlImage, type: image, base_path: '/images/', label: 'Image', sortable: false}
                    - {property: isActive, label: 'Publié'}
            form: 
                title: 'Ajouter / modifier une langue'
                fields: 
                    - {property: nom, label: Langue}
                    - {property: label, label: Code langue, type: language}
                    - {property: urlImage, label: 'URL image'}
                    - {property: isActive, label: 'Publié'}
            show:
                title: 'Afficher une langue'
                fields:
                    - {property: nom, label: Langue}
                    - {property: label, label: Code langue}
                    - {property: urlImage, label: 'URL image'}
                    - {property: isActive, label: 'Publié'}
                    - {property: solutions, label: Solutions }
                    - {property: dangerosites, label: Toxicités }
        
        Solution:
            label: 'Solutions'
            class: App\Entity\Solution
            list:
                title: 'Liste des solutions'
                fields: 
                    - nom
                    - {property: langue.urlImage, label: 'Langue',type: image, base_path: '/images/', css_class: text-center }
                    - isActive
            show:
                title: 'Afficher la solution (%%entity_id%%)'
                fields: 
                    - id
                    - nom 
                    - {property: isActive, label: Publiée }
                    - {property: langue.nom, label: Langue }
            form:
                title: 'Ajouter / modifier une solution'
                fields: 
                    - nom
                    - {property: langue, label: 'Langue'}
                    - {property: isActive, label: 'Publié'}

        Dangerosite:
            label: 'Toxicités'
            class: App\Entity\Dangerosite
            list:
                title: 'Liste des toxicités'
                fields: 
                    - id
                    - {property: typeDanger, label: 'Type de danger'}
                    - {property: phraseRisque, label: 'Phrase de risque'}
                    - {property: urlPicto, label: 'Pictogramme', type: image, base_path: '/images/'}
                    - {property: isActive, label: 'Publié'}
                    - {property: langue.label, label: 'Langue'}
            show:
                title: Fiche de toxicité
                fields: 
                    - id 
                    - typeDanger
                    - phraseRisque
                    - urlPicto
                    - {property: langue.nom, label: Langue}
                    - isActive
            form:
                title: 'Ajouter / Modifier une toxicité'
                fields: 
                    - {property: typeDanger, label: 'Type de danger'}
                    - {property: phraseRisque, label: 'Phrase de risque'}
                    - {property: urlPicto}
                    - {property: langue, label: 'Langue'}
                    - {property: isActive, label: 'Publié'}
        ProduitTeste:
            label: 'Produits testés'
            class: App\Entity\ProduitTeste
            list:
                title: 'Liste des produits testés'
                fields: 
                    - {property: id, label: ID}
                    - {property: IUPAC, label: IUPAC}
                    - {property: numeroCAS, label: 'N°CAS'}
                    - {property: dangerosite.phraseRisque, label: 'Toxicité du produit', css_class: text-center}
                    - {property: solution, label: 'Solution recommandée', css_class: text-center}
                    - {property: isMelange, label: 'Mélange'}
                    - {property: isTested, label: 'Testé'}
                    - {property: isActive, label: 'Publié' }
            
            show:
                title: 'Fiche du produit testé #%%entity_id%%'
                fields:
                    - id
                    - IUPAC
                    - numeroCAS
                    - isMelange
                    - isTested
                    - isActive
                    - 
                        property: caracteristiques
                        label: Caractéristiques
                        type_options: {raw: true}
                        #type: association
                        #fieldType: entity
                        #dataType: association
                        #virtual: true
                        #template: "@EasyAdmin/default/field_association.html.twig"
                    - { property: fichiers, label: Fichiers }
            form:
                title: 'Éditer le produit #%%entity_id%%'
                fields: 
                    #- {property: id, type_options: {disabled: true}}
                    - {property: IUPAC, label: IUPAC}
                    - {property: numeroCAS, label: 'Numéro CAS'}
                    - {property: isMelange, label: 'Ce produit est un mélange'}
                    - {property: isTested, label: 'A été testé'}
                    - {property: isActive, label: 'Publié' }
                    - {property: dangerosite, label: 'Toxicité'}
                    - {property: solution, label: 'Solution recommandée'}
                    - 
                        property: caracteristiques
                        label: Caractéristiques
                        type: collection
                        type_options:
                            entry_type: App\Form\CaracteristiqueType
                            allow_delete: true
                            allow_add: true
                            by_reference: false
                            entry_options: { label: false }
                    -
                        property: fichiers
                        label: Fichiers
                        type: collection
                        type_options:
                            entry_type: App\Form\FichierType
                            allow_delete: true
                            allow_add: true
                            by_reference: false
                            entry_options: { label: false }
            new:
                title: Ajouter un nouveau produit
                fields: 
                    - '-id'

        Melange:
            label: 'Mélanges'
            class: App\Entity\Melange

        User:
            label: 'Utilisateurs'
            class: App\Entity\User
            list:
                title: 'Liste des utilisateurs'
                fields:
                    - id
                    - {property: username, label: 'Utilisateur'}
                    - {property: email, label: 'Email'}
                    - {property: isActive, label: 'Publié'}
                    - {property: role, label: 'Accès'}
                    - 
                        property: createdAt
                        label: 'Date de création'
                        type_options: {widget: single_text}
                sort: ['username', 'ASC']
            show:
                fields:
                    - {property: id, label: 'Id'}
                    - {property: username, label: 'Utilisateur'}
                    - {property: email, label: 'Email', type: email}
                    - {property: isActive, label: 'Publié'}
                    - {property: role, label: 'Accès'}
                    - 
                        property: createdAt
                        label: 'Date de création'
                        type_options: {widget: single_text}
            form:
                title: 'Ajouter / modifier un utilisateur'
                help: 'Rôles: USER, ADMIN, SUPER_ADMIN'
                fields:
                    - {property: username, label: 'Utilisateur'}
                    - {property: email, label: 'Email', type: email}
                    - {property: role, label: 'Rôle'}
                    - {property: isActive, label: 'Publié'}
